In [1]:
import pandas as pd 
import numpy as np

In [9]:
df_train = pd.read_csv('../../../not_on_git/final_classification/train_data.csv', usecols=['name', 'ra', 'dec' , 'class'])
df_train = df_train.set_index('name')
df_train

                      class          ra        dec
name
2CXO J002359.4-720438    CV    5.997523 -72.077393
2CXO J174041.4-534004    CV  265.172853 -53.667935
2CXO J002409.2-720543    CV    6.038483 -72.095544
2CXO J002411.1-720620    CV    6.046367 -72.105583
2CXO J002401.4-720441    CV    6.005988 -72.078311
...                     ...         ...        ...
2CXO J003444.5-431554   AGN    8.685473 -43.265148
2CXO J203606.3+422737   YSO  309.026368  42.460379
2CXO J131747.5+411745   AGN  199.448025  41.295864
2CXO J023234.3-073105   AGN   38.143197  -7.518061
2CXO J103357.8+574942   AGN  158.490834  57.828580

[7703 rows x 3 columns]

In [20]:
df_cos = pd.read_csv('all-csc-all-cosmos-v3.csv', usecols=['name', 'ra', 'dec', 'angDist', 'conf_flag', 'pileup_flag', 'streak_src_flag', 'sat_src_flag', 'spec_type', 'phot_type', 'star_flag'])
df_cos = df_cos[df_cos['conf_flag']==False]
df_cos = df_cos.set_index('name')
df_cos = df_cos[df_cos['angDist']<=1]
df_cos

,angDist,ra,dec,conf_flag,pileup_flag,streak_src_flag,sat_src_flag,star_flag,spec_type,phot_type
name,,,,,,,,,,
2CXO J100317.3+014837,0.804290,10 03 17.384,+01 48 37.18,False,False,False,False,0,-9,1
2CXO J100317.4+024017,0.526664,10 03 17.441,+02 40 17.78,False,False,False,False,0,-9,1
2CXO J100317.5+021608,0.822762,10 03 17.553,+02 16 08.71,False,False,False,False,0,-9,1
2CXO J100318.6+021811,0.808124,10 03 18.699,+02 18 11.17,False,False,False,False,0,-9,1
2CXO J100319.8+020952,0.808117,10 03 19.879,+02 09 52.30,False,False,False,False,0,-9,1
...,...,...,...,...,...,...,...,...,...,...
2CXO J100316.4+024106,0.658377,10 03 16.498,+02 41 06.97,False,False,False,False,0,-9,3
2CXO J100316.5+021811,0.414377,10 03 16.508,+02 18 11.15,False,False,False,False,0,-9,3
2CXO J100316.6+022423,0.924509,10 03 16.672,+02 24 23.03,False,False,False,False,0,-9,1
2CXO J100316.9+015526,0.206203,10 03 16.964,+01 55 26.59,False,False,False,False,0,-9,3
2CXO J100316.9+020739,0.910412,10 03 16.954,+02 07 39.08,False,False,False,False,0,-9,1

In [19]:
df_all = pd.read_csv('all_clf.csv', usecols=['name', 'ra', 'dec' ,'class', 'prob'])
df_all = df_all.set_index('name')
df_cos = pd.read_csv('all-csc-all-cosmos-v3.csv', usecols=['name', 'ra', 'dec', 'angDist', 'conf_flag', 'pileup_flag', 'streak_src_flag', 'sat_src_flag', 'spec_type', 'phot_type', 'star_flag'])
df_cos = df_cos[df_cos['conf_flag']==False]
df_cos = df_cos.set_index('name')
df_cos = df_cos[df_cos['angDist']<=1]
df_cos

,angDist,ra,dec,conf_flag,pileup_flag,streak_src_flag,sat_src_flag,star_flag,spec_type,phot_type
name,,,,,,,,,,
2CXO J100317.3+014837,0.804290,10 03 17.384,+01 48 37.18,False,False,False,False,0,-9,1
2CXO J100317.4+024017,0.526664,10 03 17.441,+02 40 17.78,False,False,False,False,0,-9,1
2CXO J100317.5+021608,0.822762,10 03 17.553,+02 16 08.71,False,False,False,False,0,-9,1
2CXO J100318.6+021811,0.808124,10 03 18.699,+02 18 11.17,False,False,False,False,0,-9,1
2CXO J100319.8+020952,0.808117,10 03 19.879,+02 09 52.30,False,False,False,False,0,-9,1
...,...,...,...,...,...,...,...,...,...,...
2CXO J100316.4+024106,0.658377,10 03 16.498,+02 41 06.97,False,False,False,False,0,-9,3
2CXO J100316.5+021811,0.414377,10 03 16.508,+02 18 11.15,False,False,False,False,0,-9,3
2CXO J100316.6+022423,0.924509,10 03 16.672,+02 24 23.03,False,False,False,False,0,-9,1
2CXO J100316.9+015526,0.206203,10 03 16.964,+01 55 26.59,False,False,False,False,0,-9,3
2CXO J100316.9+020739,0.910412,10 03 16.954,+02 07 39.08,False,False,False,False,0,-9,1

In [26]:
df = pd.merge(df_cos, df_all, left_index=True, right_index=True, how='right')
df = df[df['angDist']<=1]
df

,angDist,ra_x,dec_x,conf_flag,pileup_flag,streak_src_flag,sat_src_flag,star_flag,spec_type,phot_type,ra_y,dec_y,class,prob
name,,,,,,,,,,,,,,
2CXO J095717.8+021515,0.791334,09 57 17.826,+02 15 15.74,False,False,False,False,0.0,-9.0,1.0,149.324275,2.254371,AGN,0.999750
2CXO J095722.9+023146,0.566585,09 57 22.931,+02 31 46.73,False,False,False,False,0.0,-9.0,1.0,149.345547,2.529647,AGN,0.996052
2CXO J095726.0+024501,0.367624,09 57 26.069,+02 45 01.04,False,False,False,False,0.0,-9.0,1.0,149.358621,2.750290,AGN,0.999921
2CXO J095727.0+023837,0.746436,09 57 27.039,+02 38 37.55,False,False,False,False,0.0,-9.0,3.0,149.362662,2.643763,AGN,0.999671
2CXO J095727.4+023440,0.389594,09 57 27.430,+02 34 40.29,False,False,False,False,0.0,-9.0,3.0,149.364292,2.577859,STAR,0.976716
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2CXO J100309.3+021957,0.966242,10 03 09.301,+02 19 57.94,False,False,False,False,0.0,-9.0,3.0,150.788754,2.332760,AGN,0.994529
2CXO J100310.3+015008,0.292568,10 03 10.338,+01 50 08.93,False,False,False,False,0.0,-9.0,1.0,150.793076,1.835813,AGN,0.999978
2CXO J100311.2+020820,0.488404,10 03 11.284,+02 08 20.66,False,False,False,False,0.0,-9.0,3.0,150.797018,2.139072,AGN,0.999968
2CXO J100312.0+021222,0.176673,10 03 12.085,+02 12 22.04,False,False,False,False,0.0,-9.0,3.0,150.800355,2.206122,AGN,0.999898
2CXO J100313.8+015214,0.232141,10 03 13.835,+01 52 14.60,False,False,False,False,0.0,-1.0,3.0,150.807646,1.870723,AGN,0.993293

In [20]:
df['class'].value_counts()

AGN     2199
STAR      74
Name: class, dtype: int64

In [21]:
agn = df[df['class']=='AGN']
star = df[df['class']=='STAR']

In [23]:
agn['phot_type'].value_counts()

 3.0     1451
 1.0      452
 2.0      207
-99.0      68
 5.0       21
Name: phot_type, dtype: int64

In [24]:
agn['spec_type'].value_counts()

-9.0     1045
 2.0      622
 1.0      279
-99.0     152
-1.0       74
 0.0       16
-2.0       11
Name: spec_type, dtype: int64

In [25]:
agn['star_flag'].value_counts()

0.0     2175
1.0       15
10.0       9
Name: star_flag, dtype: int64

In [27]:
star['spec_type'].value_counts()

 0.0    39
-9.0    30
 2.0     4
-1.0     1
Name: spec_type, dtype: int64

In [13]:
df_cos

,angDist,ra,dec,conf_flag,pileup_flag,streak_src_flag,sat_src_flag,star_flag,spec_type,phot_type
name,,,,,,,,,,
2CXO J100317.3+014837,0.804290,10 03 17.384,+01 48 37.18,False,False,False,False,0,-9,1
2CXO J100317.4+024017,0.526664,10 03 17.441,+02 40 17.78,False,False,False,False,0,-9,1
2CXO J100317.5+021608,0.822762,10 03 17.553,+02 16 08.71,False,False,False,False,0,-9,1
2CXO J100318.6+021811,0.808124,10 03 18.699,+02 18 11.17,False,False,False,False,0,-9,1
2CXO J100319.8+020952,0.808117,10 03 19.879,+02 09 52.30,False,False,False,False,0,-9,1
...,...,...,...,...,...,...,...,...,...,...
2CXO J100316.4+024106,0.658377,10 03 16.498,+02 41 06.97,False,False,False,False,0,-9,3
2CXO J100316.5+021811,0.414377,10 03 16.508,+02 18 11.15,False,False,False,False,0,-9,3
2CXO J100316.6+022423,0.924509,10 03 16.672,+02 24 23.03,False,False,False,False,0,-9,1
2CXO J100316.9+015526,0.206203,10 03 16.964,+01 55 26.59,False,False,False,False,0,-9,3
2CXO J100316.9+020739,0.910412,10 03 16.954,+02 07 39.08,False,False,False,False,0,-9,1

In [14]:
df_train

                      class          ra        dec
name
2CXO J002359.4-720438    CV    5.997523 -72.077393
2CXO J174041.4-534004    CV  265.172853 -53.667935
2CXO J002409.2-720543    CV    6.038483 -72.095544
2CXO J002411.1-720620    CV    6.046367 -72.105583
2CXO J002401.4-720441    CV    6.005988 -72.078311
...                     ...         ...        ...
2CXO J003444.5-431554   AGN    8.685473 -43.265148
2CXO J203606.3+422737   YSO  309.026368  42.460379
2CXO J131747.5+411745   AGN  199.448025  41.295864
2CXO J023234.3-073105   AGN   38.143197  -7.518061
2CXO J103357.8+574942   AGN  158.490834  57.828580

[7703 rows x 3 columns]

In [24]:
df_train_cosmos =  pd.merge(df_train, df_cos, left_index=True, right_index=True, how='inner')
df_train_cosmos

,class,ra_x,dec_x,angDist,ra_y,dec_y,conf_flag,pileup_flag,streak_src_flag,sat_src_flag,star_flag,spec_type,phot_type
name,,,,,,,,,,,,,
2CXO J095753.4+024735,AGN,149.472898,2.793296,0.562594,09 57 53.495,+02 47 35.87,False,False,False,False,0,1,1
2CXO J095915.0+014926,AGN,149.812891,1.823901,0.746863,09 59 15.094,+01 49 26.04,False,False,False,False,0,2,3
2CXO J100213.3+023351,AGN,150.555804,2.564187,0.622396,10 02 13.393,+02 33 51.07,False,False,False,False,0,1,1
2CXO J100110.1+023242,AGN,150.292481,2.545008,0.421803,10 01 10.195,+02 32 42.03,False,False,False,False,0,1,1
2CXO J100149.6+023853,AGN,150.456703,2.648121,0.511725,10 01 49.609,+02 38 53.23,False,False,False,False,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2CXO J095841.9+015443,AGN,149.674943,1.911968,0.199527,09 58 41.986,+01 54 43.08,False,False,False,False,0,-99,3
2CXO J100130.8+024405,AGN,150.378576,2.734979,0.419336,10 01 30.858,+02 44 05.92,False,False,False,False,0,2,2
2CXO J100025.0+024128,AGN,150.104357,2.691235,0.432977,10 00 25.046,+02 41 28.45,False,False,False,False,0,1,1
2CXO J100113.8+014000,AGN,150.307708,1.666888,0.708144,10 01 13.850,+01 40 00.80,False,False,False,False,0,-99,1
2CXO J095845.8+022007,AGN,149.691065,2.335510,0.526350,09 58 45.856,+02 20 07.84,False,False,False,False,0,2,3

In [18]:
df_train_cosmos['class'].value_counts()

AGN    217
Name: class, dtype: int64

In [29]:
ms = pd.read_csv('mystix.tsv', delimiter='|')
ms.to_csv('mystix.csv')